### ISSUE TITLE
Support of RockFluidOrganizationInterpretation

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#107]
**Is your feature request related to a problem? Please describe.**
There is no RockFluidOrganizationInterpretation support.

**Describe the solution you'd like**
I want Fesapi to support it.

**Describe alternatives you've considered**
 Attach IJKGrids to EarthModel instead

**Additional context**

**Comment by philippeVerney** [comment]
Hi Lionel,

Similar answer than to your previous feature request. This month is not the easiest one for me to answer quickly to the community. I may have more time after April 15.
However, I definitely confirm the need for this support.

In order accelerate support, think about:
- forking and making a PR
- joining the "Fesapi Initiative" to vote for your wish list.

**Comment by untereiner** [comment]
Hi Philippe,

I know you are busy. This issue acts more as a reminder. 
Mid of april is fine. I'll see if I have time and/or knowledge to make a PR during this time.

**Comment by untereiner** [comment]
Hi Philippe,

Thanks again for the help!
I have two IJKgrids in my epc file linked to a RockFluidOrganizationInterpretation. But at loading I have getGridRepresentationCount() == 0. I can not figure out why my grids are not attached to it.
Since you looked at the work, could you maybe have an idea ?

**Comment by philippeVerney** [comment]
The link is defined at line 1015 of AbstractGridrepresentation. You should point a breakpoint here.

**Comment by philippeVerney** [comment]
I have looked at the example.cpp and I don't see obvious error.

The link instantiation is in detail called line 1026 and then 1036. You should firs tlook if you indeed hit those lines for your two grids.

**Comment by untereiner** [comment]
I just looked into my file and my grid is linked to the RockFluidOrganizationInterpretation via a `representedInterpretation` and not via `CellFluidPhaseUnits->FluidOrganization`. Should it be that way as in `AbstractRepresentation` ?

**Comment by philippeVerney** [comment]
This is a pure RESQML question not a FESAPI question ("maybe" a question for the FESAPI forum). I cannot talk for the standard.
My humble opinion is that, with the design adopted by your files, you would lose some information such as which cells belong to which fluid units. Consequently my personal opinion is : in general, no it should not be that way.

I close this issue since, for fesapi, this topic is resolved. Feel free to open another one for discussion in the fesapi forum or bring the question to the standard.

Fixed in #116
