### ISSUE TITLE
PillarShape

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#159]
**Is your feature request related to a problem? Please describe.**
get the pillar Shape of a grid, same as the KDirection

**Describe the solution you'd like**
return a resqml2__PillarShape enum

**Describe alternatives you've considered**
compute the pillar shape using the pillar kind but PillarShape is stored (if I am not wrong) 

**Additional context**
/

**Comment by philippeVerney** [comment]
Hi Lionel,

I need a bit more information please because I am confused about two alternatives. Do you request:
- to get the most complex pillar shape of a RESQML (column layer) grid? (only one)
or
- to get ALL the various pillar shapes (which can be different or the same) of the (column layer) grid?

FYI, there must be only one K Direction per grid. That's not the case for the pillar shapes but it is the case for the most complex (geometry) pillar shape.
Both (most complex kind + all kinds) are stored : respectively in XML and generally in HDF5.

**Comment by philippeVerney** [comment]
It looks that you want to get the most complex pillar shape but I prefer a confirmation that we are indeed talking about the "most complex" one.

**Comment by untereiner** [comment]
Yes, sorry I wasn't precise. The most complex one. The one needed when the geometry is set (e.g. setGeometryAsCoordinateLineNodes)

**Comment by untereiner** [comment]
thanks !
