### ISSUE TITLE
File reading problem

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#189]
# What are the steps to reproduce this issue?
1. Load a file (can provide it by mail)

# What does happen?
Message:

>  The file ObjGrid2dRepresentation_e1734c86-0599-465c-84f3-7356ba7d1062.xml does not exist in the EPC document

But the epc contains this file when I look into

# What were you expecting to happen?
no error

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?
The function Package::fileExists returns false 

# What versions of fesapi are you using?
…

**Comment by philippeVerney** [comment]
Hi Lionel,

Please, send me the EPC by email.

**Comment by philippeVerney** [comment]
Notice that your xml file does not look to follow the standard naming convention "obj_" instead of "Obj" : http://docs.energistics.org/#EPC/EPC_TOPICS/EPC-000-019-0-C-sv1000.html

**Comment by philippeVerney** [comment]
Much more buggy. Your file also declare Obj instead of "obj_" in the [Content_Types].xml of your EPC.
This is critical since the type you reference does not exist at all. Fesapi warns you about in the repo (look at repo.getWarnings() after seserialization). Fesapi cannot read a file whose Content Type is unknown.

**Comment by philippeVerney** [comment]
Bug on the file (inconsistency between contentype entry and part name). No bug on fesapi => Won't fix.
