### ISSUE TITLE
Unable to create Property Kind for WITSML Channel.

### ISSUE THREAD

**Issue by Hoosayin** [F2I-Consulting/fesapi#315]
Hi Philippe!

I am following FESAPI example and I am trying to serialize wells. I am using RESQML 2.0 and EML 2.0 as default standards for DataObjectRepository. However, when I try to create Property Kind for WITSML Channel, it throws invalid argument exception since I am using EML 2.0 standard, while the constructor of Property Kind is guarded by the macro WITH_RESQML2_2. Following is the code snippet where the exception is thrown:

![image](https://github.com/F2I-Consulting/fesapi/assets/47661256/b790862d-4eb8-466a-8143-8b0a933fb69b)

Following is the code where Channel Property Kind is being created:

![image](https://github.com/F2I-Consulting/fesapi/assets/47661256/4985ca7f-4dc1-4d96-9978-24780a91e9cd)

How can we create WITSML objects if we are using RESQML 2.0 and EML 2.0 with FESAPI v2.7.1.0?

**Comment by Hoosayin** [comment]
Sorry for inconvenience. This is resolved by using overloaded member function: 

![image](https://github.com/F2I-Consulting/fesapi/assets/47661256/7bf26aeb-4abb-4dd2-8745-5f0e2d6f0a4e)

**Comment by philippeVerney** [comment]
Hi Hussain,

You got it right!
However:
- from a pure WITSML point of view, be aware that WITSML2.1 is done to work with EML2.3.
- WITSML community does not really use EPC container.
- RESQML community does not really use WITSML to serailize wells but only RESQML. For instance, logs are not transfered using WITSML channel but using RESQML WellboreFrameRepresentaiton associated to (Continuous/Discrete/Categorical)Property

**Comment by Hoosayin** [comment]
Thanks for your response. However, I didn't get the point. 

1. How can I do the same thing, "serializeWitsmlWells()", if I am using RESQML 2.0 and EML 2.0 with FESAPI v2.7.1.0? Do I have to use WITSML 2.0 classes? If so, I guess they are not available in FESAPI v2.7.1.0. 

As for now, I am using overloaded member function for creating Property Kind, the program seems to execute well, the data is written successfully. But, when I try to read the title of WITSML Well Bore that is associated with Well Bore Feature, I get exception because gsoapProxy2_3 is a nullptr. 

![image](https://github.com/F2I-Consulting/fesapi/assets/47661256/4c160b75-2615-4c79-b67a-5ea8c8f6ce17)

Here is the snippet where I am reading the title:

![image](https://github.com/F2I-Consulting/fesapi/assets/47661256/c0a45166-830a-4f0c-a46a-87ad183a602b)

If I skip this part, I am able to read everything else including Trajectory's MD Values and XYZ Points,

2. Also, when serializing WITSML Wells in Java, it seems like "eml23__UnitOfMeasure" and "eml23__DataIndexKind" are not defined in "com.f2i_consulting.fesapi". FESAPI v2.1.0.0 JAR

![image](https://github.com/F2I-Consulting/fesapi/assets/47661256/6dea3566-a8ae-45c8-b2e7-8074b242aaf7)

**Comment by philippeVerney** [comment]
So my very first question is "why do you use WITSML?" If the answer is "because it is in the example", please do not follow blindly the example and consider not using WITSML at all. 
I am afraid that you want RESQML transfer but that you use WITSML cause of the example...

Otherwise, I keep this issue opened to look at the particular bug you raise (WITSML in FESAPI is not as tested as RESQML in FESAPI)

**Comment by Hoosayin** [comment]
To be honest, I am following the example blindly. Actually, I am trying to write Wellbore Feature, Wellbore Interpretation, Wellbore Trajectory Representation, and Wellbore Frame Representation, and read them back from the server. I have achieved this already. Since, I don't know why WITSML part is there. In order to not miss anything, I was trying serialize WITSML wells too. I guess, I can skip the WITSML part. However, skipping WITSML leaves my Wellbore Feature as a Partial Object. Is it safe?

**Comment by philippeVerney** [comment]
If you don't need WITSML, my recommendation would be for you to skip it if you are RESQML focused.
The RESQML WellboreFeature should not be partial when you skip WITSML well. This bug has been solved in FESAPI 2.5 AFAIK.

If you want WITSML support what is tested as of today is:
- well (probably the most important dataobjet because it is missing from RESQML which has only got wellbore)
- wellbore
- wellboreCompletion
All the WITSML other dataobjects are subject to issues. These issues can of course be reported here (and solved) and I thank you for that.

**Comment by Hoosayin** [comment]
Thanks for your recommendation.
You're welcome. I'll keep reporting if I encounter more issues. I really appreciate your prompt replies.
