### ISSUE TITLE
std::uncaught_exception is deprecated starting at C++17

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#320]
# What are the steps to reproduce this issue?
Compile with C++17: std::uncaught_exception is deprecated starting at C++17

# What does happen?
compilation error

# What were you expecting to happen?
compilation success

# Any logs, error output, etc?
n.a.

# Any other comments?
n.a.

# What versions of fesapi are you using?
2.8.0.0

**Comment by philippeVerney** [comment]
Hi @untereiner 

[date.h](https://github.com/F2I-Consulting/fesapi/blob/master/src/tools/date.h) is a not a FESAPI code but a [Howard Hinnant one](https://github.com/HowardHinnant/date).
This issue has been discussed [several times](https://github.com/HowardHinnant/date/issues?q=uncaught+exception) upstream.
The most recent answer from Howard Hinnant seems to be [here](https://github.com/HowardHinnant/date/pull/651#issuecomment-1335316468). See also [this answer](https://github.com/HowardHinnant/date/issues/622#issuecomment-724736690).
This "issue" is then very well known and acknowledged even assumed. However, one can tell that the Howard Hinnant's decision should be revisited as he himself let think about it as he made the decision 5 (now 6) years ago.

Looking at all of that, I am a bit reluctant to take another decision than the official one in order to solve this issue.

I have personally not enough current knowledge to take any decision but think that Howard Hinnant knows the best the pros and cons regarding this issue in his code. Maybe you would want to rediscuss it upstream?
You can count on me to integrate quickly the latest version of date.h if there is a new release.

**Comment by untereiner** [comment]
Hi! Fair enough. It is not your responsibility. I will add the mentioned compiler flag in my project. On the other side I disagree with the author. The standard says « deprecated c++17 » so it’s use should be avoided starting with c++17
