### ISSUE TITLE
If I write an HDF5 file with FESAPI 2.8, is it readable with FESAPI 1.2 ?

### ISSUE THREAD

**Issue by corppeon** [F2I-Consulting/fesapi#329]
I used v2.8 to write an HDF5 file. I used HDFView to compare the data written against v1.2 writing the same data.

I see that the object paths have changed from /RESQML/xxx to /resqml20/xxx.

Does that mean that FESAPI v1.2 will not be able to read this HDF data?

**Comment by philippeVerney** [comment]
FESAPI v1.2 should read FESAPI v2.8 HDF data transparently.

Indeed the EPC file contain XML files which explicitely contain the path to the associated HDF5 dataset.
FESAPI (whatever version) reads the path in the XML of the EPC before to read the HDF5 dataset.
If it does not work, it would clearly be a bug.

PS : the change in the EPC hierarchy (organization of the XML files within the EPC) is more error prone. We know that some (older) versions of some RESQML software do not succed to read this new hierarchy in EPC but latest version are fixed and can now read it. FYI, the standard itself does not mandate any particular hierarchy in the EPC, nor in the HDF5.

**Comment by ddevienne** [comment]
Hi Philippe. Can you please share light on that _**new EPC hierarchy**_?

I haven't heard about it, and despite not directly working on EPC/ETP/RESQML right now,
I'd like to know about it, and see whether my code supports both the old and the new hierarchy.
Also, can you share EPCs with that _new hierarchy_ for testing? Thanks, --DD

**Comment by philippeVerney** [comment]
This new hierarchy in EPC has been decided in FESAPI to better differentiate XML from their various versions of Energistics standards (WITSML, PRODML, RESQML, EML and their numeric versions). Indeed, in all FESAPI v2.* I think, XML are now in some folders named "namespace_STANDARDNAMESTANDARDNUMERICVERSION".
Regarding OPC, the standard which EPC comes from, this does not matter since the content of an EPC file is described in the root [Content_Types].xml file but if a software does not read [Content_Types].xml assuming a particular arbitrary location for the XML files then it will fail.

Here is [testingPackageCpp.zip](https://github.com/F2I-Consulting/fesapi/files/12762592/testingPackageCpp.zip) which I produce from the FESAPI example project which illustrate the current XML organization in EPC which FESAPI produces.

**Comment by ddevienne** [comment]
> [...] the content of an EPC file is described in the root [Content_Types].xml file

OK, good. We are already _good citizens_ and read that TOC, so we should be fine.

> [testingPackageCpp.zip] [...] which illustrate the current XML organization in EPC which FESAPI produces.

Thanks! I'll double-check we're OK with this. I assume Laurent already knows all about this,
and you're in more frequent contact with him than I am :). I appreciate the help. Cheers, --DD

**Comment by philippeVerney** [comment]
Hi @corppeon,

Please close this issue if the answer is OK with you.
From a more general point of view, we encourage to use [discourse ](https://discourse.f2i-consulting.com/) for questions and we try to keep Github for feature requests and bugs.

**Comment by corppeon** [comment]
Thanks Philippe
