### ISSUE TITLE
Inconsistency between installation on Windows and Linux

### ISSUE THREAD

**Issue by cgodkin** [F2I-Consulting/fesapi#337]
# What are the steps to reproduce this issue?

After building FESAPI 2.8 with `cmake` on Windows and Linux, there's a slight difference in the installation output.

# What does happen?

The directory fesapi-2.8.0/include/fesapi on Linux contains the `tools` directory but Windows does not.

# What were you expecting to happen?

Include `tools` in both (or neither?) but I prefer both.

# Any other comments?

This is _extremely_ trivial and I only noticed when working on some time conversion issues.

# What versions of fesapi are you using?

2.8

**Comment by philippeVerney** [comment]
Hi Carl,

The windows intent is the correct one : the `tools` directory should not be installed. Indeed, these are considered as FESAPI internal tools and we don't want to publish them (and to maintain them out of FESAPI scope).
Looking at [my comments in CMakeLists.txt](https://github.com/F2I-Consulting/fesapi/blob/master/src/CMakeLists.txt#L319), it looks that I decided to install them on Unix because they are, by default, exported in the library. But I think this was a mistake on my side because it lead to the inconsistency you just noticed.

Thank you

**Comment by cgodkin** [comment]
I admit that I didn't try to figure out the intent from the CMakeLists.txt file.  I wrote a test program that uses something in `date.h` and I had to build it differently on Windows vs. Linux so I noticed this and wanted to point it out.  Thanks for the explanation!

**Comment by philippeVerney** [comment]
Just in case, `date.h` comes from this repository : https://github.com/HowardHinnant/date even in more recent version (w[hich conflicts with "windows.h" in FESAPI](https://github.com/HowardHinnant/date/issues/87), another issue to fix)
This is a much better source than FESAPI for using this file.
