### ISSUE TITLE
type disagreement when std::vector size() returns unsigned int

### ISSUE THREAD

**Issue by cgodkin** [F2I-Consulting/fesapi#72]
# What are the steps to reproduce this issue?

Hi Philippe,

I'm compiling with warnings again... 😉

# What does happen?

C4267 - 'return': conversion from 'size_t' to 'unsigned int', possible loss of data

Here are the locations:
resqml2/AbstractGridRepresentation.h(93)
resqml2/AbstractGridRepresentation.h(127)
resqml2_0_1/WellboreTrajectoryRepresentation.h(208)

# What were you expecting to happen?

Either static_cast<unsigned int> or change return type to size_t

# Any logs, error output, etc?

# Any other comments?

I would submit a PR but I don't know which solution you would prefer.  I imagine you don't want to change the API so probably the first.  Let me know if so.

# What versions of fesapi are you using?

Just updated to master yesterday.

**Comment by philippeVerney** [comment]
Hi Carl,

Good point.
I have chosen to avoid using size_t in .h because of non C++ support.
Indeed, I have not taken enough time about how to well support size_t typedef with swig in all different possible platforms. I guess the solution starts here : http://www.swig.org/Doc2.0/SWIG.html#SWIG_nn19

Consequently, as a quick answer, I would indeed choose to static_cast.
Longer term probably not.

I'll look for a fix when I'll have time or feel free to provide a PR.
If you provide a PR, please notice that I created a branch 0.13 which is the only developement branch for now (with etp branch).
If needed, I can copy non breaking commits (probably like this one) from 0.13 to master if a v0.12.1 is needed.
