### ISSUE TITLE
Grid2dRepresentation and setGeometryAsArray2dOfLatticePoints3d

### ISSUE THREAD

**Issue by mgimhof** [F2I-Consulting/fesapi#73]
Grid2dRepresentation allows setting the geometry both with setGeometryAsArray2dOfLatticePoints3d and setGeometryAsArray2dOfExplicitZ. 

However, the getters, e.g., get ZValues, only support Point3dZValueArray. The alternate Point3dLatticeArray is not supported. 

It would really help if the Grid2dRepresentation supported Point3dLatticeArray  more fully.

As it stands, the workaround for  the user is to try getZValues, catch the exception, and loop over offsets and spacing to reconstruct the z values. It would be nice if this could be hidden from the users.

**Comment by philippeVerney** [comment]
If I understand correctly, you want Grid2dRepresentation.getZValues working even if the underlying geometry is a Point3dLatticeArray. I think I am totally fine with that.

Where I have a doubt is when you tell `"and loop over offsets and spacing to reconstruct the z values"`. Indeed, since Fesapi does not provide z offset access for now (but only x and y offsets), I don't understand how you can even currently reconstruct the z values.
To me there is not even a workaround for now.

My second paragraph is not very important. It is just to be sure I well understood.
Could you confirm my understanding of the need (i.e my first paragraph)?

**Comment by mgimhof** [comment]
Philippe,

You are right, z offsets are not provided and so my work around is not even feasible

I would like to call Grid2dRepresentation.getZValues to get the z values both for Point3dZValueArray and Point3dLatticeArray.

It looks like Grid2dRepresentation::getZValues will need an additional comparison to  Point3dLatticeArray with some code to fill the values array with the z values.

**Comment by philippeVerney** [comment]
Thanks,
The issue is perfectly clear now. I'll work on it for version 0.13.
