### ISSUE TITLE
compilation issue on macos with gcc-8

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#90]
# What are the steps to reproduce this issue?
1. Compile fesapi on macos with gcc-8

# What does happen?
The following error:
```
In file included from /fesapi-superbuild/fesapi/src/proxies/stdsoap2.cpp:44:
/fesapi-superbuild/fesapi/src/proxies/stdsoap2.cpp: In function 'const char* soap_float2s(soap*, float)':
/fesapi-superbuild/fesapi/src/proxies/stdsoap2.h:1480:32: error: call of overloaded 'isnan(double)' is ambiguous
 #  define soap_isnan(n) isnan(n)
                                ^
/fesapi-superbuild/fesapi/src/proxies/stdsoap2.cpp:16446:7: note: in expansion of macro 'soap_isnan'
   if (soap_isnan((double)n))
       ^~~~~~~~~~
/fesapi-superbuild/fesapi/src/proxies/stdsoap2.h:1401:16: note: candidate: 'int isnan(double)'
 extern "C" int isnan(double);
                ^~~~~
In file included from /usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/math.h:36,
                 from /fesapi-superbuild/fesapi/src/proxies/stdsoap2.h:697,
                 from /fesapi-superbuild/fesapi/src/proxies/stdsoap2.cpp:44:
/usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/cmath:624:3: note: candidate: 'constexpr bool std::isnan(long double)'
   isnan(long double __x)
   ^~~~~
/usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/cmath:619:3: note: candidate: 'constexpr bool std::isnan(double)'
   isnan(double __x)
   ^~~~~
/usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/cmath:611:3: note: candidate: 'constexpr bool std::isnan(float)'
   isnan(float __x)
```

Same error for function isinf.

# What were you expecting to happen?
no error

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?
A work around consists to add `#  ifdef __clang__ ` just after `# ifdef __cplusplus` at line 1401 in stdsoap2.h and add a `#  endif` after the define function

# What versions of fesapi are you using?
master branch version

**Comment by philippeVerney** [comment]
Thanks Lionel for this report.

stdsoap2 files do not belong to fesapi but to gsoap :  https://sourceforge.net/projects/gsoap2/
I cannot modify (and redistribute) them because of licensing reasons (fesapi does not use the GPL version of gsoap).

I first need to check on the gsoap documentation if there is something told about that.
If not, I need to forward this issue directly to gsoap.

**Comment by philippeVerney** [comment]
Did the recent update to gsoap 2.8.81 solve this bug please?
It looks you could build fesapi on macos looking at #114

**Comment by untereiner** [comment]
no, I had to change the lines manually.
I think it is a bug of gsoap, maybe due to the inclusio of <math.h> and <cmath.h>

**Comment by philippeVerney** [comment]
I just forwarded the bug to gsoap : https://sourceforge.net/p/gsoap2/bugs/1243/

**Comment by philippeVerney** [comment]
As asked in https://sourceforge.net/p/gsoap2/bugs/1243/ could you try
------------------------------------
Maybe if you try the following hack in stdsoap2.cpp around line 16469 soap_float2s:

  double x = n;
  if (soap_isnan(x))

I really don't see the problem using soap_isnan((double)n) which is the same as isnan((double)n) when isnan is available.
------------------------------------

You can answer here or directly on sourceforge if you have time.

**Comment by philippeVerney** [comment]
Removing #include <cmath>from srs/tools/TimeTools.cpp can also be another try.
I will remove it in my next PR since I don't think it is used anyhow.

**Comment by untereiner** [comment]
The floor function is in the cmath header.

**Comment by philippeVerney** [comment]
If I understand well the first link, a simple test would be to simply rename `#define soap_isnan(n) isnan(n)` line 1480 with `#define soap_isnan(n) ::isnan(n)`. FYI, it is now line 1462 in current stdsoap2.h.

I cannot test on my machine because these lines are not even defined. Can you test when you'll have time and if you think that it is worth doing it.
In parallel, I am going to try to remove floor calls in src/tools/TimeTools.cpp. It is strange that my VS2015 fesapi solution does not complain about removing `#include <cmath>` even if floor calls remain.
And in other parallel, the gsoap ticket remains opened and converges to math.h and cmath inclusion conflict.

**Comment by untereiner** [comment]
Postfixing isnan with :: does not work

**Comment by philippeVerney** [comment]
Thanks Lionel,

I am going to remove cmath inclusion in my next PR (I just comment the method which contains floor call since this function is no more used with the abandon of DAS support in Fesapi)
In parallel, I did deeper research and think to have a new direction to solve the problem directly in gsoap. If you are interested, you can give a look at my last post in https://sourceforge.net/p/gsoap2/bugs/1243/ (this is really only for information)

**Comment by untereiner** [comment]
I check your post. Nice work! It is maybe the reason that adding ifdef __clang__ just between those lines make it work!

**Comment by philippeVerney** [comment]
Can you confirm that removing the two lines 1383 and 1384 of stdsoap2.h resolve your problem?
If so, it looks gsoap agrees to change that. I will of course update fesapi when the upgraded version of gsoap will be out.
It might subsist some risks for old (pre version 6) gcc releases on MacOS.

**Comment by philippeVerney** [comment]
Actually it is more than jsut two lines.

The new block would look:
```
#ifdef __APPLE__
# ifndef HAVE_ISNAN
#  define HAVE_ISNAN
# endif
# ifndef HAVE_ISINF
#  define HAVE_ISINF
# endif
#endif
```

**Comment by philippeVerney** [comment]
@untereiner : Did you have a chance to test my two posts above?
The ticket is now on "pending-fixed" status on gsoap side.

**Comment by untereiner** [comment]
Using the new block of code works on macos with gcc 8.3
